version: '2'
services:
  web:
    image: mhart/alpine-node:6
    volumes:
      - .:/usr/local/blog.howarddierking.com
    environment:
      - GITHUB_COMMIT=3327743
    ports:
      - "80:8080"
    command: /usr/local/blog.howarddierking.com/serve.sh
