version: '2'
services:
  web:
    image: node:6
    volumes:
      - .:/usr/local/blog.howarddierking.com
    expose: 
      - "8080"
    ports:
      - "80:8080"
    command: /usr/local/blog.howarddierking.com/entrypoint.sh
